jakartaee/jakartaone.org

- .travis.yml
- config.toml
> Deploy save the date page on production

- content/_index.md
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>
> Remove title and breadcrumb from home page

- .project
- data/committee.yml
- layouts/index.html
- layouts/partials/program-committee.html
- layouts/program-committee/section.html
- less/custom.less
Converted committee members to be data objects to be reused. Tweaked CSS
around match height class to have a min-height of 50 to fix issue around
absolute children of containers. Made minor updates to committee member
profiles.
Change-Id: I21c2a1fc8d7aa9bf2497f3059725566af7bfff92
> Tech debt: Use data/list obejcts to leverage Hugo for committee... #11

- content/_index.md
- layouts/index.html
- layouts/partials/about.html
- layouts/partials/get-social.html
- less/custom.less
- package-lock.json
> Horizontal scrollbar at fullwidth for home page #14 #15

- layouts/partials/program-committee.html
Change-Id: I3b280c163f10c6021aa6b355ba03b455651c0190
> Content mistake in JakartaOne Livesrtream #17

- data/agenda.yml
Change-Id: I5385cc8ee231ed80e20ea948ab7c4565d165de91
> Updated Jakarta Servlet: A new Twist on an Old Favourite VOD link

- data/agenda.yml
Replace crowdcast links with youtube
> Addling recording links to jakartaone.org #41

- layouts/index.html
- less/custom.less
> Shrink jumbotron further #46

- content/japan2020/_index.md
- content/japan2020/program-committee.md
- data/japan2020/agenda.yml
- data/japan2020/committee.yml
> adding initial data files for japan2020

- config.toml
- content/japan2020/_index.jp.md
- i18n/jp.toml
> add CFP site and minor collections

- content/_index.jp.md
- content/speaker-agreement.jp.md
- content/speaker-agreement.md
> Speakers Agreement for JakartaOne Livestream conferences #62

- config.toml
> Add Speaker Agreement to main menu

- content/_index.md
- content/japan2020/_index.jp.md
- content/japan2020/_index.md
> Fix for HREFs missing quotes

- content/japan2020/_index.jp.md
- content/japan2020/_index.md
- data/en/japan2020/agenda.yml
- data/jp/japan2020/agenda.yml
> update agenda and registration

- data/en/japan2020/agenda.yml
- data/jp/japan2020/agenda.yml
> update Red Hat speaker

- data/event_config.yml
- i18n/en.toml
- i18n/jp.toml
- layouts/partials/footer_custom.html
Added small custom config framework for adding event specific
configuration values through data/event_config.yml. Added initial value
of twitter_handle for update to social section
> twitter handle for specific event #80

- data/en/japan2020/registration.yml
- data/jp/japan2020/registration.yml
> JakartaOne Japan 2020 event closed #83

- .travis.yml
- content/_index.jp.md
- content/_index.md
- layouts/shortcodes/alert.html
- netlify.toml
- package-lock.json
- package.json
> Hugo 62.2 and solstice 59 upgrade

- data/en/japan2020/agenda.yml
- data/jp/japan2020/agenda.yml
> add vido links to japan2020

- data/en/cn4j2020/agenda.yml
- data/en/cn4j2020/speaker.yml
> Adding Sessions and Speakers #99

- data/en/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
> Date listed for first Jakartaone livestream is incorrect #104

- layouts/shortcodes/past_events.html
- less/custom.less
> Future vs. past event tiles are indistinguishable #105

- config.toml
> Translate website in Portuguese #97

- data/en/brazil2020/registration.yml
- data/pt/brazil2020/registration.yml
> Create a button link to C4P [Jakarta One Brazil] #114

- data/en/cn4j2020/registration.yml
> Update the JakartaOne Livestream CN4J page #116

- content/2020/_index.md
- data/en/2020/default/registration.yml
- package-lock.json
- package.json
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>
> Add CFP button for JakartaOne 2020

- content/2020/hispano/_index.es.md
- content/2020/hispano/_index.md
- data/en/2020/hispano/registration.yml
- data/es/2020/hispano/registration.yml
> Jakarta Hispano, add the ABOUT THE EVENT section and standardize the button to apply for the CFP

- config.toml
- content/2020/_index.md
- data/en/2020/default/registration.yml
- layouts/partials/nav.html
> Create a section for CFP #132

- data/en/2020/brazil/registration.yml
- data/pt/2020/brazil/registration.yml
> Add a register button [Jakarta One Live Brazil] #158

- layouts/partials/head_custom.html
- package-lock.json
- package.json
Change-Id: I9272fcf710bbd5a92743d319683f14f4a14f9ddb
> Use open sans google font

- content/2020/hispano/_index.es.md
- content/2020/hispano/_index.md
[JakartaOne In Spanish] "Community Partner" section #159
Change-Id: I6a99433d81421d02650b9cd2deba29487d189fe7
> remove become a sponsor

- content/2020/brazil/_index.md
- content/2020/brazil/_index.pt.md
> Remove the "Become a Sponsor" button [Jakarta One Live Brazil] #169

- data/en/2020/default/committee.yml
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>
> Fix errors in PC titles

- data/en/2020/brazil/agenda.yml
- data/pt/2020/brazil/agenda.yml
Signed-off-by: otaviojava <otaviopolianasantana@gmail.com>
> update Jakarta one Brazil agenda

- data/en/2020/hispano/registration.yml
Signed-off-by: jonathan <jvilalop@redhat.com>
> Hispano register button

- content/2020/_index.md
- data/en/2020/default/registration.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
> add register now button and changed words

- content/2020/hispano/_index.es.md
- content/2020/hispano/_index.md
- data/en/2020/hispano/agenda.yml
- data/en/2020/hispano/committee.yml
- data/es/2020/hispano/agenda.yml
- data/es/2020/hispano/committee.yml
- data/es/2020/hispano/registration.yml
Signed-off-by: Hillmer Chona <hilac@msn.com>
> Hispano agenda and registration

- content/2020/brazil/_index.md
- content/2020/brazil/_index.pt.md
- data/en/2020/brazil/agenda.yml
- data/en/2020/brazil/registration.yml
- data/pt/2020/brazil/agenda.yml
- data/pt/2020/brazil/registration.yml
Fix #190 
We use text to make that content more accessible and configurable for the banner.
> update Brazil banner and agenda to videos

- config.toml
- content/2020/_index.md
- package-lock.json
- package.json
- webpack.mix.js
One of https://github.com/EclipseFdn/jquery-eclipsefdn-api/issues/16
> update theme, add featured footer

- content/2020/hispano/_index.es.md
- content/2020/hispano/_index.md
- data/en/2020/hispano/agenda.yml
- data/en/2020/hispano/registration.yml
- data/es/2020/hispano/agenda.yml
- data/es/2020/hispano/registration.yml
Fix #214
Signed-off-by: Hillmer Chona <hilac@msn.com>
> Updating JakartaOne in Spanish to reflect event completion

- config.toml
- content/2020/_index.md
- content/2020/code-of-conduct.md
- data/en/2020/default/agenda.yml
> add jakartaOne 2020 agenda #218

- content/2020/_index.md
> Fix Date in title when hovering

- data/en/2020/default/agenda.yml
> Solves github issue 229 by adding co-speaker for JakartaOne session 2020

- data/en/2020/default/agenda.yml
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>
> Replace demo tag with microprofile

- data/en/2020/default/agenda.yml
> Update schedule #227

- data/en/2020/default/agenda.yml
> Update 2020 jakartaone schedule session title #233

- data/en/2020/default/agenda.yml
> JakartaOne 2020 Schedule Updates - Studio Jakarta EE #235

- data/en/2020/default/agenda.yml
Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>
> Add interview with Werner

- content/2020/_index.md
- content/2020/hispano/_index.md
- data/en/2020/default/agenda.yml
- data/en/2020/default/registration.yml
> update agenda to reflect finished #239

- .travis.yml
- less/styles.less
- netlify.toml
- package-lock.json
- package.json
- webpack.mix.js
> Update theme to 0.0.111

- data/en/2020/default/agenda.yml
> #251 Fix livestream 2020 Dec 8 broken youtube links

- content/2021/russian/_index.md
- content/2021/russian/_index.ru.md
Fix #254 
~~Sadly we don't have translation currently, I am asking again. Let me confirm whether they will provide translation or we just go with English page.  https://github.com/jakartaee/jakartaone.org/issues/254#issuecomment-776793502~~
We have the translation. I updated the text.
Should be ready now. 
Got +1 from https://github.com/jakartaee/jakartaone.org/issues/254#issuecomment-776812748 and https://github.com/jakartaee/jakartaone.org/issues/254#issuecomment-776814728
> Activate call for paper

- content/2021/russian/_index.md
- content/2021/russian/_index.ru.md
> Close call for paper

- content/2021/russian/_index.md
- content/2021/russian/_index.ru.md
- data/en/2021/russian/agenda.yml
- data/en/2021/russian/registration.yml
- data/ru/2021/russian/agenda.yml
- data/ru/2021/russian/registration.yml
> Update JakartaOne Russian to Reflect Event... #277

- content/_index.es.md
- content/_index.jp.md
- content/_index.md
- content/_index.pt.md
- content/_index.ru.md
- content/_index.tr.md
For [issue290](https://github.com/jakartaee/jakartaone.org/issues/290)
> Changed main banner to promot Turkish event

- content/2021/turkish/_index.md
- content/2021/turkish/_index.tr.md
- data/en/2021/turkish/registration.yml
- data/tr/2021/turkish/registration.yml
> Add Call for Papers to JakartaOne Turkish Website #292

- data/en/2021/portuguese/committee.yml
Signed-off-by: Otavio Santana <otaviopolianasantana@gmail.com>
> updates otavio's profile

- content/2021/portuguese/_index.md
- content/2021/portuguese/_index.pt.md
> Jakarta EE - Portuguese Call for Papers #299

- content/2021/hispano/_index.es.md
- content/2021/hispano/_index.md
Updated title to the registration section for now open CFP.
Fixes #308
> JakartaOne Livestream Spanish-CFP Open #308

- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
Changes wrong date of the 30th on homepage
> Date for Portuguese event is inconsistent #311

- content/2021/hispano/_index.es.md
- content/2021/hispano/_index.md
- content/2021/portuguese/_index.md
- content/2021/portuguese/_index.pt.md
> CFP closing dates should be more easily discovered #310

- content/2021/portuguese/_index.md
- content/2021/portuguese/_index.pt.md
Fixes [issue318](https://github.com/jakartaee/jakartaone.org/issues/318)
> Updated call for paper status to now closed

- content/2021/hispano/_index.es.md
- content/2021/hispano/_index.md
- data/en/2021/hispano/registration.yml
- data/es/2021/hispano/registration.yml
> JakartaOne Livestream Spanish Website Update #322

- data/en/2021/turkish/agenda.yml
- data/tr/2021/turkish/agenda.yml
Fixes [issue330](https://github.com/jakartaee/jakartaone.org/issues/330)
> Added YouTube videos

- content/2021/turkish/_index.md
- content/2021/turkish/_index.tr.md
Fixes [issue330](https://github.com/jakartaee/jakartaone.org/issues/330)
> Replaced the buttons with Jakarta EE logo

- data/en/2021/portuguese/agenda.yml
- data/pt/2021/portuguese/agenda.yml
Fixes [issue336](https://github.com/jakartaee/jakartaone.org/issues/336)
> Updated the presentation title

- data/en/2021/hispano/agenda.yml
- data/es/2021/hispano/agenda.yml
Signed-off-by: Eudris Cabrera <eudris@gmail.com>
> updating agenda

- content/2021/_index.md
- data/en/2021/default/registration.yml
Fixes [issue340](https://github.com/jakartaee/jakartaone.org/issues/340)
> Updated Call for papers section

- data/en/2021/default/agenda.yml
Fixes [issue349](https://github.com/jakartaee/jakartaone.org/issues/349)
> Switched the order of 2 sessions

- package.json
- webpack.mix.js
- yarn.lock
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>
> Update solstice theme and webpack

- data/en/2021/default/agenda.yml
Fixes [issue352](https://github.com/jakartaee/jakartaone.org/issues/352)
> Updated the agenda

- content/2021/_index.md
- data/en/2021/default/agenda.yml
- less/components/agenda.less
- package.json
- yarn.lock
Fixe [issue352](https://github.com/jakartaee/jakartaone.org/issues/352)
> Updated agenda for JakartaOne

- content/2021/_index.md
- content/_index.md
- data/en/2021/default/agenda.yml
- data/en/2021/default/registration.yml
- data/en/conferences.yml
Fixes https://github.com/jakartaee/jakartaone.org/issues/355
> Updated about event content

- package.json
- yarn.lock
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>
> Update hugo theme version

- content/2022/_index.md
- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
- content/_index.es.md
- content/_index.jp.md
- content/_index.md
- content/_index.pt.md
- content/_index.ru.md
- content/_index.tr.md
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
- layouts/shortcodes/active-events.html
- package.json
- yarn.lock
Fixes https://github.com/jakartaee/jakartaone.org/issues/361
> Updated jakartaone.org landing page

- i18n/de.toml
German translation for JakartaOne German
> German transaltion added

- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
- content/2022/portuguese/program-committee.md
- content/2022/portuguese/program-committee.pt.md
- data/en/2022/portuguese/committee.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/2022/portuguese/committee.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
For https://github.com/jakartaee/jakartaone.org/issues/367
> Added committee fomr JakartaOne 2022 - Portuguese

- content/2021/portuguese/program-committee.pt.md
- content/2022/german/_index.de.md
- content/2022/german/_index.md
- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
- content/2022/portuguese/program-committee.md
- content/2022/portuguese/program-committee.pt.md
- data/de/2022/german/registration.yml
- data/en/2022/german/registration.yml
For https://github.com/jakartaee/jakartaone.org/issues/365#issuecomment-1128923505
> Updated the event description and cfp note

- data/en/2022/portuguese/committee.yml
- data/pt/2022/portuguese/committee.yml
> Updated Otavio's title

- content/2022/german/_index.de.md
- content/2022/german/_index.md
- data/de/2022/german/agenda.yml
- data/de/2022/german/committee.yml
- data/de/2022/german/registration.yml
- data/en/2022/german/agenda.yml
- data/en/2022/german/committee.yml
- data/en/2022/german/registration.yml
- less/components/registration.less
For https://github.com/jakartaee/jakartaone.org/issues/365
> Updated German 2022 agenda and registration info

- data/de/2022/german/speakers.yml
- data/en/2022/german/speakers.yml
@ericpoirier I fixed an typo and added Will Lyons to the speakers (with exisiting picture).
WARNING: I based this branch on the current master state, so proper merging the changes from the german-update-4 branch will be necessary!
I will review the changes in this PR with the preview soon.
> German update 5

- content/2022/german/_index.de.md
- content/2022/german/_index.md
- data/de/2022/german/registration.yml
- data/en/2022/german/registration.yml
https://github.com/jakartaee/jakartaone.org/issues/365
> feat: Remove call for papers and proposals buttons on DE event page

- content/2022/japan/_index.md
- content/2022/japan/program-committee.md
- data/de/conferences.yml
- data/en/2022/japan/committee.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
https://github.com/jakartaee/jakartaone.org/issues/385
> feat: Create Japan event page and Add program-committee

- content/2022/japan/_index.jp.md
- content/2022/japan/_index.md
- data/en/2022/japan/agenda.yml
- data/jp/2022/japan/agenda.yml
- data/jp/2022/japan/committee.yml
> add japanese page for Japan 2022 event

- content/2022/japan/_index.jp.md
- content/2022/japan/_index.md
> add cfp for Japan

- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
https://github.com/jakartaee/jakartaone.org/issues/367
> feat: Add Call for Papers button for 29 sep event

- content/2022/german/_index.de.md
- content/2022/german/_index.md
- data/de/2022/german/agenda.yml
- data/de/2022/german/registration.yml
- data/en/2022/german/agenda.yml
- data/en/2022/german/registration.yml
https://github.com/jakartaee/jakartaone.org/issues/365
> feat: Remove registration text and buttons

- data/en/2022/japan/agenda.yml
- data/jp/2022/japan/agenda.yml
> add payara session

- content/2022/japan/_index.jp.md
- content/2022/japan/_index.md
- data/en/2022/japan/agenda.yml
- data/jp/2022/japan/agenda.yml
> add session details

- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
- data/en/2022/portuguese/agenda.yml
- data/pt/2022/portuguese/agenda.yml
Issue https://github.com/jakartaee/jakartaone.org/issues/367
> feat: Create agenda + Add registration

- data/en/2022/japan/agenda.yml
- data/jp/2022/japan/agenda.yml
> add payara abstract

- data/en/2022/portuguese/agenda.yml
- data/pt/2022/portuguese/agenda.yml
Updating talk titles from Paulo Simoes, Karina and Otávio.
> Updating two talks in the jakartaonept agenda

- content/2022/japan/_index.jp.md
- content/2022/japan/_index.md
- data/en/2022/japan/agenda.yml
- data/jp/2022/japan/agenda.yml
> Japan event concluded

- data/en/2022/default/organizers.yml
This PR adds Shabnam's bio for the Dec 09 2022 livestream event
> Add bio for Shabnam

- content/2022/portuguese/_index.md
- content/2022/portuguese/_index.pt.md
- data/en/2022/portuguese/agenda.yml
- data/en/2022/portuguese/registration.yml
- data/pt/2022/portuguese/agenda.yml
- data/pt/2022/portuguese/registration.yml
Resolves https://github.com/jakartaee/jakartaone.org/issues/428
> feat: Update Portuguese event to concluded

- data/en/2022/default/registration.yml
> Add registration link for JakartaOne Livestream 2022

- data/de/conferences.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
- data/zh/conferences.yml
- layouts/shortcodes/past_events.html
> Organize past events under a year section

- content/2022/_index.md
- data/en/2022/default/agenda.yml
> Add agenda for JakartaOne Livestream 2022

- config.toml
- netlify.toml
> [hot-fix] - fix dates for jakartaone.org

- content/2022/_index.md
- layouts/shortcodes/events/program-committee.html
- less/components/program-committee.less
Resolves part of #447 
Bug fix
> Fix overflow issues with project committee shortcode

- layouts/partials/footer_links/footer-copyright.html
> Remove duplicate social media row in footer

- data/en/2022/default/agenda.yml
> Add legend and update agenda rows

- data/en/2022/default/agenda.yml
> Keep studio sessions consistent

- data/en/2022/default/agenda.yml
> Add Industry Keynote speakers

- content/2022/_index.md
- data/en/2022/default/registration.yml
> Conclude JakartaOne 2022 event page

- content/_index.de.md
- content/_index.es.md
- content/_index.jp.md
- content/_index.md
- content/_index.pt.md
- content/_index.ru.md
- content/_index.tr.md
- content/_index.zh.md
> Replace download link on homepage with "host an event" link

- data/en/2022/default/agenda.yml
> Add VODs for 2022 Livestream

- data/en/2022/default/agenda.yml
> Remove Jakarta EE Studio session that doesn't have a video

- content/2023/_index.md
- content/_index.md
- data/en/2023/default/registration.yml
- data/en/conferences.yml
> JakartaOne Livestream 2023 EN

- content/2023/_index.md
- content/2023/spanish/_index.md
- data/en/conferences.yml
> Add JakartaOne Spanish 2023

- content/2023/portuguese/_index.md
- data/en/conferences.yml
> Add JakartaOne Portuguese 2023

- content/2023/chinese/_index.md
- data/en/conferences.yml
> Add JakartaOne Chinese 2023

- content/2023/_index.md
> Add registration link

- data/en/2023/default/committee.yml
> Update Tobias' title

- content/2023/_index.md
> Add CFP button for 2023 EN

- content/2023/_index.md
> feat(event): Update JakartaOne 2023 registration link

- content/2023/chinese/_index.md
- content/2023/chinese/_index.zh.md
> fix: Add modals for agenda

- data/zh/2023/chinese/registration.yml
Resolves https://github.com/jakartaee/jakartaone.org/issues/501
> feat: Conclude chinese Jakartaone event for 2023-09-27

- content/2023/_index.md
> feat: remove cfp for jakartaone 2023 en

- content/2023/_index.md
- data/en/2023/default/agenda.yml
- less/styles.less
> feat: add agenda for JakartaOne 2023 EN

- data/en/2023/chinese/agenda.yml
- data/zh/2023/chinese/agenda.yml
> feat: add vods for chinese 2023 event

- data/en/2023/default/registration.yml
> feat: add conclusion text for JakartaOne 2023 EN

- data/en/2023/spanish/agenda.yml
- data/es/2023/spanish/agenda.yml
> feat: add vods for JakartaOne Spanish 2023

- content/2023/_index.md
- content/2024/portuguese/_index.md
- content/2024/portuguese/_index.pt.md
- data/en/2023/default/agenda.yml
- less/styles.less
> feat: final agenda for en

- data/en/2023/spanish/agenda.yml
- data/es/2023/spanish/agenda.yml
> feat: add more vods for JakartaOne Spanish 2023

- data/en/2023/default/agenda.yml
> feat: remove presenter

- data/en/2023/default/agenda.yml
> feat: add vods for jakartaone 2023

- content/2023/_index.md
- data/en/2023/default/registration.yml
> feat: add better conclusion text

- data/en/2024/portuguese/agenda.yml
- data/pt/2024/portuguese/agenda.yml
- Portuguese translation for Igor's talk;
- Update Bruno Souza's talk info;
> JakartaOne Livestream Portuguese 2024 - Event updates

- content/2024/_index.md
- content/2024/chinese/_index.md
- content/2024/chinese/_index.zh.md
- content/_index.de.md
- content/_index.es.md
- content/_index.jp.md
- content/_index.md
- content/_index.pt.md
- content/_index.ru.md
- content/_index.tr.md
- content/_index.zh.md
- data/de/conferences.yml
- data/en/2024/chinese/registration.yml
- data/en/2024/default/registration.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
- data/zh/2024/chinese/registration.yml
- data/zh/conferences.yml
Resolves #542 
Also updates homepage videos.
> feat: add jakartaone 2024 for en and zh

- content/2023/_index.md
> feat: remove register button

- content/2024/portuguese/_index.md
- content/2024/portuguese/_index.pt.md
- data/en/2024/portuguese/registration.yml
- data/pt/2024/portuguese/registration.yml
> feat: conclude portuguese event

- content/2024/_index.md
> feat: close cfp for jakartaone 2024 EN

- content/2024/chinese/_index.md
- content/2024/chinese/_index.zh.md
> feat: remove cfp for chinese 2024 event

- content/2024/_index.md
- data/en/2024/default/agenda.yml
> feat: update agenda with jakarta ee studio sessions

- content/2024/_index.md
- data/en/2024/default/registration.yml
> feat: conclude jakartaone 2024

- data/en/2024/default/agenda.yml
> feat: add vods

- content/2025/_index.html
- data/de/conferences.yml
- data/en/2025/default/hosts.yml
- data/en/2025/default/registration.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
- data/zh/conferences.yml
- layouts/shortcodes/active-events.html
- less/components/registration.less
- less/pages/homepage.less
> feat(en): jakartaone 2025

- content/past-events/index.de.md
- content/past-events/index.es.md
- content/past-events/index.jp.md
- content/past-events/index.ru.md
- content/past-events/index.tr.md
- content/past-events/index.zh.md
Adding the missing markdown content entries for past-events page.
Resolves #547
> chore(i18n): adding missing past-events content entries

- content/2024/chinese/_index.md
- content/2024/chinese/_index.zh.md
- data/en/2024/chinese/agenda.yml
- data/zh/2024/chinese/agenda.yml
> feat: add agenda for JakartaOne Chinese 2024

- content/2025/china/_index.html
- data/de/conferences.yml
- data/en/2025/china/registration.yml
- data/en/conferences.yml
- data/es/conferences.yml
- data/jp/conferences.yml
- data/pt/conferences.yml
- data/ru/conferences.yml
- data/tr/conferences.yml
- data/zh/conferences.yml
- i18n/en.toml
- layouts/_default/home.html
> feat(china): create new event page
